### ISSUE TITLE
打包main.js的结果过大，达到1.4M

### ISSUE THREAD

**Issue by breg-jjb** [MrRaindrop/weex_extend_demo#1]
我看到webpack.config.js中使用了这个插件：
var sourceMapPlugin = new webpack.SourceMapDevToolPlugin({
  test: /.js$/
})
请问这是干嘛的呢？
我试了一下，不用这个插件打包main.js的结果只有400k+

**Comment by MrRaindrop** [comment]
你好，这个插件是用来生成 sourcemap 的，方便在页面里做源码调试用。详见[这里](https://webpack.github.io/docs/list-of-plugins.html#sourcemapdevtoolplugin)

包大小的问题：
1. 首先这个例子只是用来做示范，所以没有打压缩代码
2. 内联了 soucemap，这部分也会占不少体积

你可以尝试用 uglify 压缩并去掉注释试试看，体积会减少一些。
